/*
 * PizzeriaPrincipal.java
 *
 * Created on 21/12/2021, 09:27:52 AM
 */
package lapizzeria;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 * @author Luis C. Puerta
 */
public class PizzeriaPrincipal extends javax.swing.JFrame 
{
    ArrayList arrayClientes = new ArrayList(); //define un array para guardar los nombres de los clientes
    ArrayList arrayValores = new ArrayList(); //define un array para guardar los valores de la cuenta
    DefaultListModel modeloClientes = new DefaultListModel(); //define un modelo para poderlo añadir al JList
    DefaultListModel modeloValores = new DefaultListModel(); //define un modelo para poderlo añadir al JList
    /** Creates new form PizzeriaPrincipal */
    public PizzeriaPrincipal() 
    {
        initComponents();
        setLocationRelativeTo(null); //centrar el JFrame en la pantalla
        //this.getContentPane().setBackground(new Color(254, 132, 2));
        this.getContentPane().setBackground(new Color(103, 167, 95));
        jlClientes.setModel(modeloClientes); //le pone el modelo al JList
        jlValores.setModel(modeloValores); //le pone el modelo al JList
        grupoTamanio.add(rbGrande);
        grupoTamanio.add(rbMediana);
        grupoTamanio.add(rbPequenia);
        grupoTamanio.add(rbNinguno);
        grupoPorciones.add(rb1);
        grupoPorciones.add(rb2);
        grupoPorciones.add(rb3);
        grupoPorciones.add(rb0);
        rbNinguno.setSelected(true); //lo selecciona
        rb0.setSelected(true); //lo selecciona
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoTamanio = new javax.swing.ButtonGroup();
        grupoPorciones = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jpDatosCli = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtTelefonos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jpDetallesPed = new javax.swing.JPanel();
        jpTamanio = new javax.swing.JPanel();
        rbMediana = new javax.swing.JRadioButton();
        rbGrande = new javax.swing.JRadioButton();
        rbPequenia = new javax.swing.JRadioButton();
        rbNinguno = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        chbChampiniones = new javax.swing.JCheckBox();
        chbSalami = new javax.swing.JCheckBox();
        chbQueso = new javax.swing.JCheckBox();
        chbPeperoni = new javax.swing.JCheckBox();
        chbGuacamole = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        rb3 = new javax.swing.JRadioButton();
        rb0 = new javax.swing.JRadioButton();
        cbBebidas = new javax.swing.JComboBox();
        jpListado = new javax.swing.JPanel();
        jpClientes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlClientes = new javax.swing.JList();
        jpValores = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlValores = new javax.swing.JList();
        jLabel6 = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        jpBotoneraControl = new javax.swing.JPanel();
        btnCalcular = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnMostrarListado = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("* * * LA PIZZERIA * * *");

        jpDatosCli.setBackground(new java.awt.Color(255, 204, 153));
        jpDatosCli.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 51))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setText("Nombre");

        txtTelefonos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setText("Teléfonos");

        txtNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setText("Dirección");

        txtDireccion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setText("Correo electrónico");

        txtCorreo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jpDatosCliLayout = new javax.swing.GroupLayout(jpDatosCli);
        jpDatosCli.setLayout(jpDatosCliLayout);
        jpDatosCliLayout.setHorizontalGroup(
            jpDatosCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDatosCliLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(190, 190, 190)
                .addComponent(jLabel3)
                .addGap(215, 215, 215)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 243, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(127, 127, 127))
            .addGroup(jpDatosCliLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(txtTelefonos, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jpDatosCliLayout.setVerticalGroup(
            jpDatosCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDatosCliLayout.createSequentialGroup()
                .addGroup(jpDatosCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDatosCliLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jpDatosCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDatosCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(2, 2, 2)
                        .addGroup(jpDatosCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtTelefonos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jpDatosCliLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jpDetallesPed.setBackground(new java.awt.Color(255, 204, 153));
        jpDetallesPed.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalles del pedidio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 51))); // NOI18N

        jpTamanio.setBackground(new java.awt.Color(255, 204, 153));
        jpTamanio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tamaño", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 51))); // NOI18N

        rbMediana.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbMediana.setText("Mediana");

        grupoTamanio.add(rbGrande);
        rbGrande.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbGrande.setText("Grande");

        rbPequenia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbPequenia.setText("Pequeña");

        rbNinguno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbNinguno.setText("Ninguno");

        javax.swing.GroupLayout jpTamanioLayout = new javax.swing.GroupLayout(jpTamanio);
        jpTamanio.setLayout(jpTamanioLayout);
        jpTamanioLayout.setHorizontalGroup(
            jpTamanioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTamanioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpTamanioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbMediana)
                    .addComponent(rbNinguno)
                    .addComponent(rbPequenia)
                    .addComponent(rbGrande))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jpTamanioLayout.setVerticalGroup(
            jpTamanioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTamanioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbNinguno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rbGrande)
                .addGap(18, 18, 18)
                .addComponent(rbMediana, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rbPequenia)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "adiciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 51))); // NOI18N

        chbChampiniones.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chbChampiniones.setText("Champiñones");

        chbSalami.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chbSalami.setText("Salami");

        chbQueso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chbQueso.setText("Queso");

        chbPeperoni.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chbPeperoni.setText("Peperoni");

        chbGuacamole.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chbGuacamole.setText("Guacamole");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(chbChampiniones, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(chbSalami)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(chbPeperoni)
                    .addComponent(chbQueso)
                    .addComponent(chbGuacamole))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(chbChampiniones)
                .addGap(15, 15, 15)
                .addComponent(chbSalami)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chbQueso)
                .addGap(18, 18, 18)
                .addComponent(chbPeperoni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chbGuacamole)
                .addGap(18, 18, 18))
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Porciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 51))); // NOI18N

        rb1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rb1.setText("1");

        rb2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rb2.setText("2");

        rb3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rb3.setText("3");

        rb0.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rb0.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb0)
                    .addComponent(rb2)
                    .addComponent(rb3)
                    .addComponent(rb1))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(rb0)
                .addGap(18, 18, 18)
                .addComponent(rb1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rb2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(rb3)
                .addContainerGap())
        );

        cbBebidas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ninguna", "Gaseosa", "Jugo en agua", "Jugo en leche", "Cerveza", "Malteada" }));

        jpListado.setBackground(new java.awt.Color(255, 204, 153));
        jpListado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 51))); // NOI18N

        jpClientes.setBackground(new java.awt.Color(255, 204, 153));
        jpClientes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jlClientes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jScrollPane1.setViewportView(jlClientes);

        javax.swing.GroupLayout jpClientesLayout = new javax.swing.GroupLayout(jpClientes);
        jpClientes.setLayout(jpClientesLayout);
        jpClientesLayout.setHorizontalGroup(
            jpClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
        );
        jpClientesLayout.setVerticalGroup(
            jpClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
        );

        jpValores.setBackground(new java.awt.Color(255, 204, 153));
        jpValores.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Valores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jlValores.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jScrollPane2.setViewportView(jlValores);

        javax.swing.GroupLayout jpValoresLayout = new javax.swing.GroupLayout(jpValores);
        jpValores.setLayout(jpValoresLayout);
        jpValoresLayout.setHorizontalGroup(
            jpValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpValoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpValoresLayout.setVerticalGroup(
            jpValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpListadoLayout = new javax.swing.GroupLayout(jpListado);
        jpListado.setLayout(jpListadoLayout);
        jpListadoLayout.setHorizontalGroup(
            jpListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpListadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpValores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jpListadoLayout.setVerticalGroup(
            jpListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpListadoLayout.createSequentialGroup()
                .addGroup(jpListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpValores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 51));
        jLabel6.setText("Valor $:");

        lblValor.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblValor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jpDetallesPedLayout = new javax.swing.GroupLayout(jpDetallesPed);
        jpDetallesPed.setLayout(jpDetallesPedLayout);
        jpDetallesPedLayout.setHorizontalGroup(
            jpDetallesPedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDetallesPedLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jpDetallesPedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpDetallesPedLayout.createSequentialGroup()
                        .addComponent(jpTamanio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(cbBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(jpDetallesPedLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblValor, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jpListado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jpDetallesPedLayout.setVerticalGroup(
            jpDetallesPedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDetallesPedLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDetallesPedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDetallesPedLayout.createSequentialGroup()
                        .addComponent(jpListado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(95, 95, 95))
                    .addGroup(jpDetallesPedLayout.createSequentialGroup()
                        .addGroup(jpDetallesPedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpDetallesPedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jpTamanio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addGroup(jpDetallesPedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDetallesPedLayout.createSequentialGroup()
                                .addComponent(lblValor, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDetallesPedLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(63, 63, 63))))))
        );

        jpBotoneraControl.setBackground(new java.awt.Color(255, 204, 153));
        jpBotoneraControl.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Botonera de control", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 51))); // NOI18N

        btnCalcular.setBackground(new java.awt.Color(255, 153, 51));
        btnCalcular.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCalcular.setForeground(new java.awt.Color(0, 0, 51));
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnNuevo.setBackground(new java.awt.Color(255, 153, 51));
        btnNuevo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(0, 0, 51));
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnMostrarListado.setBackground(new java.awt.Color(255, 153, 51));
        btnMostrarListado.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMostrarListado.setForeground(new java.awt.Color(0, 0, 51));
        btnMostrarListado.setText("Listar");
        btnMostrarListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarListadoActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(255, 153, 51));
        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(0, 0, 51));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpBotoneraControlLayout = new javax.swing.GroupLayout(jpBotoneraControl);
        jpBotoneraControl.setLayout(jpBotoneraControlLayout);
        jpBotoneraControlLayout.setHorizontalGroup(
            jpBotoneraControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBotoneraControlLayout.createSequentialGroup()
                .addGroup(jpBotoneraControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpBotoneraControlLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(95, 95, 95)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(96, 96, 96))
                    .addGroup(jpBotoneraControlLayout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)))
                .addComponent(btnMostrarListado, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jpBotoneraControlLayout.setVerticalGroup(
            jpBotoneraControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBotoneraControlLayout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jpBotoneraControlLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jpBotoneraControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular)
                    .addComponent(btnNuevo)
                    .addComponent(btnMostrarListado, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(jpBotoneraControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jpDetallesPed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jpDatosCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(392, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(369, 369, 369))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpDatosCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpDetallesPed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpBotoneraControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*
Para hacer que una clase capture los eventos es necesario usar otra palabra reservada: implements,
que sirve para agregar interfaces a las clases, y que se usa también en la línea de declaración de
éstas, después de la sentencia extends (si existe); se puede implementar más de una interfaz.
Todos los programas que requieran responder al clic de un Mouse usarán la interfaz ActionListener
que nos obliga a agregar el método actionPerformed() a nuestra clase (las interfaces son clases
especiales y casi siempre exigen que se agreguen métodos específicos). Los clics capturados remitirán
el flujo del programa al método actionPerformed() que recibe como parámetro objetos de la clase ActionEvent. 
*/
private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
    int vrTamanio, vrPorcion, vrChamp, vrGuacam, vrPeper, vrQues, vrSalam, vrBebida, vrTotal;
    String datoCliente, datoValor;
    
    vrTamanio = vrPorcion = vrChamp = vrGuacam = vrPeper = vrQues = vrSalam = vrBebida = 0;
    if(rbGrande.isSelected()) {
        vrTamanio=10000;
    }
    else
    {
        if(rbMediana.isSelected()) {
            vrTamanio = 6000;
        }
        else
        {
            if(rbPequenia.isSelected()) {
                vrTamanio = 3000;
            }
        }
    }
    if(rb1.isSelected()) {
        vrPorcion = 3000; 
    }
    else
    {
        if(rb2.isSelected()) {
            vrPorcion = 6000;
        }
        else
        {
            if(rb3.isSelected()) {
                vrPorcion = 9000;
            }
        }
    }
    if(chbChampiniones.isSelected()) {
        vrChamp = 2000;
    }
    if(chbGuacamole.isSelected()) {
        vrGuacam = 2000;
    }
    if(chbPeperoni.isSelected()) {
        vrPeper = 2000;
    }
    if(chbQueso.isSelected()) {
        vrQues = 2000;
    }
    if(chbSalami.isSelected()) {
        vrSalam = 2000;
    }
    switch(cbBebidas.getSelectedIndex())
    {
        case 0:
            vrBebida = 0;
            break;
        case 1:
            vrBebida = 2000;
            break;
        case 2:
            vrBebida = 2500;
            break;
        case 3:
            vrBebida = 3500;
            break;
        case 4:
            vrBebida = 3000;
            break;
        case 5:
            vrBebida = 4000;
            break;
        default:break;
    }
    
    vrTotal = vrTamanio+vrPorcion+vrChamp+vrGuacam+vrPeper+vrQues+vrSalam+vrBebida;
    lblValor.setText(Integer.toString(vrTotal));
    datoCliente = txtNombre.getText();
    arrayClientes.add(datoCliente);
    datoValor = lblValor.getText();
    arrayValores.add(datoValor);
}//GEN-LAST:event_btnCalcularActionPerformed

private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
    System.exit(0);
}//GEN-LAST:event_btnSalirActionPerformed

private void btnMostrarListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarListadoActionPerformed
    int i;
    modeloClientes.removeAllElements(); //limpia el modelo
    modeloValores.removeAllElements();
    for(i=0;i<arrayClientes.size(); i++)
    {
        modeloClientes.addElement(arrayClientes.get(i));
        modeloValores.addElement(arrayValores.get(i));
    }
}//GEN-LAST:event_btnMostrarListadoActionPerformed

private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
    limpiarControles();
}//GEN-LAST:event_btnNuevoActionPerformed

private void limpiarControles(){
    txtNombre.setText("");
    txtTelefonos.setText("");
    txtDireccion.setText("");
    txtCorreo.setText("");
    rbNinguno.setSelected(true);
    rb0.setSelected(true);
    cbBebidas.setSelectedIndex(0);
    chbChampiniones.setSelected(false);
    chbSalami.setSelected(false);
    chbQueso.setSelected(false);
    chbPeperoni.setSelected(false);
    chbGuacamole.setSelected(false);
    lblValor.setText("");
    txtNombre.requestFocusInWindow(); //o txtNombre.requestFocus();
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PizzeriaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PizzeriaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PizzeriaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PizzeriaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PizzeriaPrincipal().setVisible(true);                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnMostrarListado;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox cbBebidas;
    private javax.swing.JCheckBox chbChampiniones;
    private javax.swing.JCheckBox chbGuacamole;
    private javax.swing.JCheckBox chbPeperoni;
    private javax.swing.JCheckBox chbQueso;
    private javax.swing.JCheckBox chbSalami;
    private javax.swing.ButtonGroup grupoPorciones;
    private javax.swing.ButtonGroup grupoTamanio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList jlClientes;
    private javax.swing.JList jlValores;
    private javax.swing.JPanel jpBotoneraControl;
    private javax.swing.JPanel jpClientes;
    private javax.swing.JPanel jpDatosCli;
    private javax.swing.JPanel jpDetallesPed;
    private javax.swing.JPanel jpListado;
    private javax.swing.JPanel jpTamanio;
    private javax.swing.JPanel jpValores;
    private javax.swing.JLabel lblValor;
    private javax.swing.JRadioButton rb0;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JRadioButton rbGrande;
    private javax.swing.JRadioButton rbMediana;
    private javax.swing.JRadioButton rbNinguno;
    private javax.swing.JRadioButton rbPequenia;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefonos;
    // End of variables declaration//GEN-END:variables
}
